const LegalData = [
    {
        id: "1",
        title: 'Disclaimer',
        content: `<ol><li>The website <a href="https://www.9eye.in">www.9eye.in</a> and mobile applications (hereinafter referred to as the “Platform”) is the property of the <b>Nioeye Solutions Pvt. Ltd.</b> (“Company”), and neither the Company nor its directors, either alone or jointly,  represents or claims or affiliated or controlled by the Government of India, any State Government, any Government departments and institutions or any statutory or local body.</li><br/>
                    <li>The company will make its best efforts to deal with any technical issues affecting the Platform (such as, for instance, the Platform becoming inoperative). However, the company does not warrant that the user will be able to use the platform at all times or locations or the services provided through the platform will be uninterrupted or error-free or that the defects will be corrected by the Company.</li><br/>
                    <li>The user acknowledges and undertakes that use of the platform by the user is at the user’s own discretion and risk and the wser is solely responsible for any damage resulting from the use of the platform.</li><br/>
                    <li>We shall neither be liable nor responsible for any actions or inactions of users nor any breach of conditions, representations or warranties by the sellers or manufacturers of the products and hereby expressly disclaim and any all responsibility and liability in that regard. However, we may mediate or resolve any dispute or disagreement between the buyer and the sellers of the products.</li><br/>
                    <li>The company does not directly or indirectly, allow or solicit or sell or attempt to sell or offer to sell or solicit the sale or offer to purchase any products or services which are prohibited for sale in India under any law for the time being in force.</li><br/>
                    <li>THE CONTENT ON THE PLATFORM AND SERVICES ARE PROVIDED TO YOU ON AN "AS-IS" AND "AS AVAILABLE" BASIS. THE COMPANY MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE CONTENT OR OPERATION OF THE PLATFORM OR THE SERVICES. YOU EXPRESSLY AGREE THAT YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK. THE COMPANY MAKES NO REPRESENTATIONS, WARRANTIES OR GUARANTEES, EXPRESS OR IMPLIED, REGARDING THE ACCURACY, RELIABILITY OR COMPLETENESS OF THE CONTENT ON THE PLATFORM OR SERVICES, AND EXPRESSLY DISCLAIMS ANY WARRANTIES OF NON-INFRINGEMENT OR FITNESS FOR A PARTICULAR PURPOSE. THE COMPANY MAKES NO REPRESENTATION, WARRANTY OR GUARANTEE THAT THE CONTENT THAT MAY BE AVAILABLE THROUGH THE PLATFORM OR THE SERVICES IS FREE OF INFECTION FROM ANY VIRUSES OR OTHER CODE OR COMPUTER PROGRAMMING ROUTINES THAT CONTAIN CONTAMINATING OR DESTRUCTIVE PROPERTIES OR THAT ARE INTENDED TO DAMAGE, SURREPTITIOUSLY INTERCEPT OR EXPROPRIATE ANY SYSTEM, DATA OR PERSONAL INFORMATION.</li></ol>`

    }, {
        id: "2",
        title: 'Privacy Policy',
        content: `<p>In this User Privacy Policy, the words &ldquo;you&rdquo; and &ldquo;your&rdquo; refer to each customer or service user or site visitor or user. &ldquo;we&rdquo;, us&rdquo;, &ldquo;our&rdquo; or &ldquo;company&rdquo; refer to Nioeye Solutions Pvt. Ltd. The User Privacy Policy govern your use of the website, mobile application and services available under the domain www.9eye.in and mobile applications (hereinafter referred to as the &ldquo;<em>Platform</em>&rdquo;).</p>
                <p>By using the platform, you agree to be bound by the following: (1) User Privacy Policy; (2) User Terms of Use; (3) Refund &amp; return Policy; and (4) Disclaimer including any future amendments herein. That this User Privacy Policy and User Terms of Use shall hereinafter may be referred to collectively as the &ldquo;Policies&rdquo;. You also agree that by using the platform or use any of the services, made available on the platform, you have read and understood the Policies mentioned herein, as together the said Policies forms a binding agreement (the &ldquo;Agreement") between you and the company regarding your use of the platform&nbsp; and the services provided herein.</p>
                <p>This User privacy policy ("Privacy Policy") is our commitment with respect to online privacy and we recognise and fulfil appropriate protection &amp; management of Personal Information as shared by you with us.</p>
                <ol>
                    <li><strong>AGE CONFIRMATION</strong> - You affirm and confirm that you are more than 18 (Eighteen) years of age, having sound mind, with free will and without any coercion or undue influence and fully able and competent to enter into the agreement, policies, terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms of Use and Policies. If You are under the age of 18 (Eighteen) years it is deemed that you are using the platform under parental/guardian sponsor or supervision, and in accordance with applicable law.</li><br />

                    <li><strong>ACCEPTANCE</strong>
                    <ol>
                        <li>The following privacy policy governs your use of the platform, services, materials and documents being made available to you (collectively the &ldquo;<em>Services</em>&rdquo;). By creating an account on the platform or by using the Services, you signify electronically your agreement to all Policies, terms, conditions, and notices contained or referenced herein and to comply in accordance with the present privacy policy.<br /> </li>
                        <li>If you do not agree to be bound by these Privacy Policy and other policies, you may not use the Site in any way.<br /> </li>
                        <li>If this Privacy Policy conflicts with any other document, this Privacy Policy will prevail for the purposes of usage of the Site.<br /> </li>
                    </ol>
                    </li><br />

                    <li><strong>AMENDMENT</strong>- You agree that the company reserves the right, and has the sole discretion to amend any clauses by way of amendment, addition, variation or repeal or revise this Privacy Policy and other policy at any time. Your continued use of the platform or the Services following the posting of any changes to the Privacy Policy of any other policy constitutes your acceptance of those changes.</li><br />

                    <li><strong>WE PLEDGE TO-</strong>
                        <ol>
                            <li>Be transparent about the different types of information we collect and how we use them. Ask your permission before sharing your Personally Identifiable Information with third parties for purposes other than to provide services, and to do so only when we think they will provide you with a welcome additional service.<br /> </li>
                            <li>Use best-in-class data security tools to keep your data safe and protect your information from unauthorized access.<br /> </li>
                            <li>By using this service, you agree to allow us to collect and process information as described below. If you have any questions, please contact us at <a href="mailto:support@9eye.in">support@9eye.in</a> call at the phone number listed on <a href="https://www.9eye.in">www.9eye.in</a>.</li>
                        </ol>
                    </li><br />

                    <li><strong>INFORMATION THAT MAY BE COLLECTED FROM YOU?</strong>
                        <ol>
                        <li>We collect the details provided by you on registration together with information we learn about you from your use of our service and your visits to the platform and other websites accessible from them.<br /> </li>
                        <li>Kindly note that we do not collect your Payment Card details (i.e. credit/debit card number, expiration date, CVV etc.). We may collect information in connection with your participation in any promotions or contests offered by us and the information you provide when giving us feedback or completing profile forms. We also monitor customer traffic patterns and platform use, which enables us to improve the service we provide. We will collect only such information as is necessary and relevant to us to provide you with the services available on the platform.<br /> </li>
                        <li>While you use the platform, we may have automatic access to (receive and collect) certain anonymous information in standard usage logs through our web server, obtained from cookies sent to your browser from web server cookies stored on your hard drive, including but not limited to:
                            <ol>
                                <li>Computer-identification information;</li>
                                <li>IP address, assigned to the computer which you use;</li>
                                <li>The domain server through which you access our service;</li>
                                <li>The type of computer you are using; and</li>
                                <li>The type of web browser you are using.</li>
                            </ul>
                        </li>

                        <li>While you register on our platform personally identifiable information collected about you may include:
                            <ol>
                                <li>First and last name;</li>
                                <li>Email addresses;</li>
                                <li>Contact details including phone numbers;</li>
                                <li>PIN/ZIP code. - Demographic profile (like your age, gender, occupation, address and durables owned);<br /> </li>
                            </ol>
                        </li>

                        <li>We may also collect the following information about:
                            <ol>
                                <li>The pages you visit/access;</li>
                                <li>The links you click on our platform;</li>
                                <li>The number of times you access the page;</li>
                                <li>Things you view, add to bag, add to wish list; and</li>
                                <li>Other websites you open simultaneously while browsing on ours.</li>
                            </ol>
                        </li>

                        <li>You may terminate your account at any time by writing to us at <a href="mailto:support@9eye.in">support@9eye.in</a> from the email ID you have used for creating your account login, and mentioning &ldquo;Please close my account&rdquo; in the subject line. However, your information may remain stored in archive on our servers even after the deletion or termination of your account.<br /> </li>
                    </ol><br />
                <li>HOW DO WE USE THE INFORMATION IT COLLECTS?<br /> We use this information to provide and improve our Services. We may use your email address to send you this information, or to ask you to participate in surveys about your services use. We use service providers to perform some of these functions. Those service providers are restricted from sharing your information for any other purpose. We use industry standard methods to keep this information safe and secure while transmitted over your home network and through the Internet to our cloud servers.</li><br />
                <li>WITH WHOM WE SHARE MY INFORMATION?<br /> Under no circumstance do we share Personally Identifiable Information for any commercial or marketing purpose unrelated to the delivery of our service without asking you first. Our service technicians and other employees have supervised access to your information. We will disclose information to law enforcement, or to comply with other legal requests, only if provided with sufficient and appropriate legal process.</li><br />
                <li>HOW LONG DOES WE SAVE MY PERSONAL INFORMATION AND HOW CAN I DELETE IT?<br /> We store your Personally Identifiable Information on cloud servers for as long as you remain our customer in order to provide you with the service.. All information is encrypted and cannot easily be accessed.</li><br />
                <li>BROWSER COOKIES- We may use cookies to enhance user experience or for delivery of our services. Our web servers automatically collect limited information about your computer connection to the Internet, including your IP address, when you visit the platform.</li><br />
                <li>INFORMATION FROM PROMOTIONS- We collect information you give us when you participate in a promotion. Specifically, you will typically be asked to provide your name and email address, and possibly other information such as your mailing address and telephone number.</li><br />
                <li>OTHER INFORMATION- We may retain any data you provide to us in an email inquiry, for the purpose of tracking the types of questions we receive.</li><br />
                <li>CHANGES TO THIS POLICY- We may from time to time update this privacy policy. In the event that we merge with, or is acquired by another company, a change to this privacy policy may result. Whenever a change to this policy is significant, we will place a prominent notice on this platform.</li><br />
                <li>YOUR CONSENT- By using the Products and Services you consent to the collection and use of information by the Company. If we decide to change our Privacy Policy, we will post those changes on this page so that you are always aware of what information we collect, how we use it, and under what circumstances we disclose it. Regardless of any changes we make to our Privacy Policy, we will always use your personal information in accordance with the version of the policy in place at the time you provide your information, unless you give your express consent for us to do otherwise.</li><br />
                <li>OTHER WEBSITES- For your convenience, this platform contains links to other websites, including some websites administered by the company or administered by other companies on behalf of us, as well as to websites unrelated to us. This privacy policy does not apply to these linked websites. Each website should be checked for its own privacy policy.</li><br />
                <li>UPDATING ACCOUNT INFORMATION- We do not collect sensitive personal data like; financial information such as Bank Account details or Credit Card or Debit Card or other payment related details; physical and mental or other health conditions or medical records and history; Biometric information such as finger-prints, voice &amp; facial patterns and DNA any other sensitive information which is confidential or sensitive by its nature. We do not store information of users like the password of your email account. However, we cannot guarantee encryption or the privacy of your personal or sensitive details.</li><br />
                <li>DISCLOSURE OF YOUR PERSONAL INFORMATION- You agree and confirm that we do not rent, sell, or share Personal Information about you with other people (save with your consent) or non-affiliated companies except to provide our Services or under the following circumstances;<br />
                    <ol>
                        <li>To provide the Personal Information to trusted partners who work on behalf of or with us under confidentiality agreements. These entities may use your Personal Information to help us communicate with you about offers from us and our marketing partners;<br /> </li>
                        <li>To respond to summons, court orders, or legal process, or to establish or exercise our legal rights or defend against legal claims to share Personal Information in order to investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of Terms of Use, or as otherwise required by law;<br /> </li>
                        <li>To transfer Personal Information about you if we are acquired by or merged with another company. In this event, we will notify you before information about you is transferred and becomes subject to a different privacy policy.<br /> </li>
                        <li>To transfer Personal Information about you to trusted partners, may or may not for gain, to promote certain products/services for commercial purposes, without any prior notice to you.<br /> </li>
                        <li>Please remember that if you post any of your Personal Information in public areas of the platform such as in online forums or chat rooms, or in the platform's searchable resume database, such information may be collected and used by others over whom we have no control. We are not responsible for the use made by third parties of information you post or otherwise make available in public areas of platform.<br /> </li>
                    </ol>
                </li><br />
                <li>WHAT SECURITY PROCEDURES ARE IN PLACE TO PROTECT INFORMATION FROM LOSS, MISUSE OR ALTERATION
                    <ol>
                        <li>To protect your privacy and security, we will verify your identity before granting access or making changes to your personally identifying information. If you have registered your profile on <a href="https://www.9eye.in">www.9eye.in</a>, your User ID and Password are required in order to access your profile information.</li>
                        <li>Although we will endeavour to safeguard the confidentiality of your personally identifiable information, transmissions made by means of the Internet cannot be made absolutely secure. By using this platform, you agree that we will have no liability for disclosure of your information due to errors in transmission or unauthorised acts of third parties.<br /> </li>
                        <li>We follow generally accepted industry standards to protect the personal information and email addresses submitted to us, both during transmission and once we receive it. No method of transmission over the Internet, or method of electronic storage, is 100% secure, however. Therefore, while we strive to use commercially acceptable means to protect your personal information and email address, we cannot guarantee its absolute security.<br /> </li>
                        <li>All information gathered on the site is securely stored within our controlled database. The database is stored on servers secured behind a firewall; access to the servers is password-protected and is strictly limited. However, as effective as our security measures are, no security system is impenetrable. We cannot guarantee the security of our database, nor can we guarantee that the information you supply will not be intercepted while being transmitted to us over the Internet and, of course, any information you include in a posting to the discussion areas is available to anyone with internet access.<br /> </li>
                    </ol>
                </li><br />
                <li>DISCLAIMER- The Company does not access, store or keep credit card data. Accordingly, the Company shall not be responsible or liable for any loss or damage due to any disclosure whatsoever of Personal Information. The Company shall not be liable for any loss or damage sustained by reason of any disclosure (inadvertent or otherwise) of any Personal Information concerning the User's account and / or information relating to or regarding online transactions using credit cards / debit cards and / or their verification process and particulars nor for any error, omission or inaccuracy with respect to any information so disclosed and used.</li><br />
                <li>ASSIGNABILITY- The Company may assign any of its responsibilities/obligations to any other person without notice to the User, at its sole discretion. However, you shall not assign, sub-licence or otherwise transfer any of your rights under this Privacy Policy to any other party, unless a written consent is taken from the Company.</li><br />
                <li>GRIEVANCE The Company shall address any discrepancies and grievances that you may have regarding the platform or use of the Services in a time bound manner. For this purpose, the Company has designated a grievance officer who shall redress the grievances within one month from the date of receipt of the grievance.<br /><br />
                <strong>Grievance officer details</strong><br />
                Name: Sahil Rajput<br />
                Designation: Grievance Officer<br />
                Email ID: <a href="mailto:support@9eye.in">support@9eye.in</a>
                </li><br/>
                <li>SECURITY- We protect information both online and off-line. The transmission of information is encrypted and protected using Secure Sockets Layer (SSL).</li>
            </ol>

`

    }, {
        id: "3",
        title: 'Terms and Conditions',
        content: `<p>In these User Terms of Use, the words &ldquo;you&rdquo; and &ldquo;your&rdquo; refer to each customer or service user or site visitor or user. &ldquo;Merchant&rdquo; refers to each seller on our platform. &ldquo;we&rdquo;, us&rdquo;, &ldquo;our&rdquo; or &ldquo;company&rdquo; refer to Nioeye Solutions Pvt. Ltd. The terms of use govern your use of the website and services available under the domain <a href="https://www.9eye.in">www.9eye.in</a> and Mobile platform (hereinafter referred to as the &ldquo;Website&rdquo;).</p>
                <p>By using this website, you agree to be bound by the following: (1) User Terms of Use; (2) User Privacy Policy; (3) Refund &amp; Return Policy and (4) Disclaimer including any future amendments herein. That the User Terms of Use, User Privacy Policy, Refund &amp; Return policy and Disclaimer shall hereinafter may be referred to collectively as the <em>&ldquo;Policies&rdquo;</em>. You also agree that by using this website or use any of the services, made available on this website, you have read and understood the Policies mentioned herein, as together the said Policies forms a binding agreement (the<em> &ldquo;Agreement</em>") between you and the company regarding your use of this website and the services provided herein.</p>
                <ol>
                <li><strong>AGE CONFIRMATION- </strong>You affirm and confirm that you are more than 18 (Eighteen) years of age, having sound mind, with free will and without any coercion or undue influence and fully able and competent to enter into the agreement, policies, terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms of Use and Policies. If You are under the age of 18 (Eighteen) years it is deemed that you are using the website under parental/guardian sponsor or supervision, and in accordance with applicable law.</li><br />
                <li><strong>ACCEPTANCE-</strong>
                <ol>
                <li>The following Terms of Use govern your use of the website, services, materials and documents being made available to you (collectively the &ldquo;<em>Services</em>&rdquo;). By creating an account on the website or by using the Services, you signify electronically your agreement to all Policies, terms, conditions, and notices contained or referenced herein and to comply in accordance with the present Terms of Use.</li>
                <li>If you do not agree to be bound by these User Terms of Use and other policies, you may not use the website in any way.</li>
                <li>If this User Terms of Use conflicts with any other document, the User Terms of Use will prevail for the purposes of usage of the website.</li>
                <li>If you use the website, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer to prevent unauthorised access to your account. You agree to accept responsibility for all activities that occur under your account or password. You should take all necessary steps to ensure that the password is kept confidential and secure and should inform us immediately if you have any reason to believe that your password has become known to anyone else, or if the password is being, or is likely to be, used in an unauthorised manner. Please ensure that the details you provide us with are correct and complete and inform us immediately of any changes to the information that you provided when registering. You can access and update much of the information you provided us with in the Your Account area of the website. You agree and acknowledge that you will use your account on the website to purchase products only for your personal use and not for business purposes. The company reserves the right to refuse access to the website, terminate accounts, remove or edit content at any time without notice to you.</li>
                <li>The Company offers the online marketplace service to you through the websites. The actual contract for sale is directly between the Merchant and you. We provide the services of listing catalogues, pricing, shipping, etc. which is informational and it is up to you to follow it or not. We shall not mediate or resolve any dispute or disagreement between you and the Merchant. We has no control over: (a) the existence, quality, safety or legality of items displayed; (b) the accuracy of third party content or listings including that of registered Merchants; (c) the ability of Merchant&rsquo;s or sellers to sell items; (d) the ability of buyers to pay for items. We do not, at any point of time during any transaction between buyer and Merchant, take the ownership of any of the goods offered by the Merchant. Nor does we, at any point, assert any rights or claims over the goods or services offered by the Merchant to the buyer.</li>
                <li>The Company, through the website also makes available a variety of branded products/ services offered by its Merchant partners. Purchase of such products will be subject to the terms of offer for sale, and such other additional terms, if any, as specified by the Merchant. The Company is a facilitator and does not take any legal responsibility for the authenticity or quality of such branded products/services and customers are encouraged to exercise prudence and diligence (including by viewing any available customer reviews of the products or services or the Merchant) before purchasing such products or availing such services.</li>
                <li>The Company may offer delivery services through its logistics/courier partners for some of the products on the website, which may be changed by the Company without any notice to you.</li>
                <li>The Company is not a warrantor of the products/ services being offered on the website by various Merchants. You acknowledge that the Company gives no warrantee/guarantee, either express or implied, regarding the product bought by you or for the use or availability of online marketplace service. Customers are encouraged to exercise prudence and diligence (including by viewing any available customer reviews of the products or services or the Merchant) before purchasing such products or availing such services.</li>
                <li>The price of products offered on the website is MRP, retail price, sale price, discounted price as offered by our Merchant partner. The Company does not either directly or indirectly influence the price of the products offered by the Merchant partner. the Company is not liable for any manufacturing defect, faulty product received, warranty claims, after sales service for any of the products purchased on the website. The Company is not linked with any warranty, guarantee, post-sale claims, genuineness of products or brand, as it is just a platform that facilitates sales for its Merchant partners. the Company will make best efforts to assist customers in issue resolution including refund or arranging replacement but it will not bear the risk from legal claims for any misrepresentation or selling of wrong product.</li>
                <li>The website makes available general third party information such as, product catalogues, lists of authorized dealers and reports on news, entertainment, technology and features, advertisements, images and photographs of the products and other data from external sources hereinafter &ldquo;Third Party Content&rdquo;). Similar Third Party Content would also be available to you on the email received by you from the Company. The provision of Third Party Content is for general informational purposes only. You acknowledge that the Third Party Content provided to you is obtained from sources believed to be reliable. the Company does not provide any guarantee with respect to any of the Third Party Content and the Company shall not be held liable for any loss suffered by you based on your reliance on or use of such Third Party Content.</li>
                <li>The company reserves the right to cancel any orders and promo code used for placing the order will not be refunded as per this cancellation policy. An order can be cancelled if it meets any of the following mentioned criteria, which includes but is not limited to (i) Products ordered are not for self-consumption but for commercial resale; (ii) Multiple orders placed for same product at the same address; (iii) Bulk quantity of the same product ordered; (iii) Invalid address given in order details; or (iv) Any malpractice used to place the order.</li>
                </ol>
                </li><br />
                <li><strong>Delivery of the Product:</strong>
                <ol>
                <li>Your purchased product shall be delivered on the address as provided by you. In the event your order is not serviceable by our logistics partners or the Merchant or the area is not covered, we would request you to provide us with an alternate shipping address which we expect to have on our partner/Merchant&rsquo;s delivery list. In case there is any dispute regarding the shipment of the product or services for the area not covered by the company, in such cases the company will not be responsible for the non-delivery of the product.</li>
                <li>In case you book multiple orders for the products and services in one transaction, the company would endeavour to ship all products together. However, this may not always be possible due to some product characteristics or logistical issues. If you purchase multiple products in a single transaction, then all the products would be dispatched to a single shipping address given by you. If you wish to ship products to different addresses, then you should book the orders separately based on the delivery addresses. Products shall be delivered by the Courier Partner at the address given by the customer while making the purchase and the company shall not be held responsible in case the address shared was incorrect.</li>
                </ol>
                </li><br />
                <li><strong>Cancellation by the company</strong>- There may be certain orders that the company&rsquo;s Merchant partners are unable to accept and service and these may need to be cancelled. Some situations that may result in your order being cancelled include, non-availability of the product or quantities ordered by you, non- availability of the delivery service in the address to which product is required to be shipped, inaccuracies or errors in pricing information specified by our Merchant partners, problems identified by the company&rsquo;s credit and fraud avoidance department or due to any major technical snag. The company may also require additional verifications or information before accepting any order. The company will contact you if all or any portion of your order is cancelled or if additional information is required to accept your order. If your order is cancelled after your credit card or bank account has been charged, the said amount will be reversed back in your credit card / bank account. A promo code, once used, shall not be refunded in case of cancellation of order either by you or the company.</li><br />
                <li><strong>Cancellation by the customer</strong>- In case of requests for order cancellations, the company reserves the right to accept or reject requests for order cancellations for any reason whatsoever. As part of usual business practice, if the company receives a cancellation notice and the order has not been processed/ approved by the company, the company shall cancel the order and refund the entire amount to you. The company will not be able to cancel orders that have already been partially or fully processed. The company has the full right to decide whether an order has been processed or not or whether an order has been partially or fully processed. You agree not to dispute the decision made by the company and accept the company&rsquo;s decision regarding the cancellation. In cases where it is not possible to cancel orders since they have already been shipped, refund shall be made subject to the return process post return request is raised and you would get replacement or refund once the original item is back with the Merchant partner in good sale-able condition.</li><br />
                <li><strong>AMENDMENT- </strong>You agree that the company reserves the right, and has the sole discretion to amend any clauses by way of amendment, addition, variation or repeal or revise these Terms of Use and other policy at any time. Your continued use of the website or the Services following the posting of any changes to the Terms of Use of any other policy constitutes your acceptance of those changes.</li><br />
                <li><strong>USE OF WEBSITE AND MOBILE APPLICATION-</strong>
                <ol>
                <li>You agree to use the website and the Services as provided on it, only in a manner which is permitted by the policies and the law. You further agree to never misuse the same. In case the Company finds any non-compliance by you of the Policies, the Company may suspend your account on the website or stop providing you the Services.</li>
                <li>It is agreed by you that by using our website or Services, it does not give you ownership of any Intellectual Property Rights in them or the content that you access. Further, by using the Services you are not granted the right to use any branding or logos used in them and you are prohibited from removing, or altering any information displayed in or along with our Products and Services.</li>
                </ol>
                </li><br />
                <li><strong>USER CONTENT</strong>
                <ol>
                <li>Some areas of the website and the Services, allow you to make available certain information such as your name, email address, phone number, address or other information or in the process of using any of the Services shall constitute "User Content". The Company claims no ownership rights over any User Content provided by you; however, by sharing such information, you agree to allow us or others to view and/or share your User Content in accordance with your settings in the use of Services. Further, the Company shall not retain any of the User Content for longer than is required for the purposes for which the User Content may lawfully be used. </li>
                <li>Further, you agree not to post or transmit any User Content that: (i) may create a risk of harm, loss, physical or mental injury, emotional distress, death, disability, disfigurement, or physical or mental illness to you, to any other person, or to any animal; (ii) may create a risk of any other loss or damage to any person or property; (iii) seeks to harm or exploit children by exposing them to inappropriate content, asking for personally identifiable details or otherwise; (iv) may constitute or contribute to a crime or tort; (v) contains any information or content that we deem to be unlawful, harmful, abusive, racially or ethnically offensive, defamatory, infringing, invasive of personal privacy or publicity rights, harassing, humiliating to other people (publicly or otherwise), libellous, threatening, profane, or otherwise objectionable; (vi) contains any information or content that is illegal (including, without limitation, the disclosure of insider information under securities law or of another party's trade secrets); (vii) contains any information or content that you do not have a right to make available under any law or under contractual or fiduciary relationships; (viii) contains any information or content that you know is not correct and current; (ix) violates any policy or other applicable policy, including those related to cheating or ethics; (x) interferes with other users of the website or Services including, without limitation, disrupting the normal flow of dialogue in an interactive area of the website and Services and deleting or revising any content posted by another person or entity. You agree that any information that you post does not and will not violate third party rights of any kind, including without limitation any Intellectual Property Rights (as defined below) or rights of privacy. The Company reserves the right, but is not obligated, to reject and/or remove any such information that it believes, in its sole discretion, violates these provisions.</li>
                </ol>
                </li><br />
                <li><strong>INTELLECTUAL PROPERTY RIGHTS</strong>
                <ol>
                <li>The trademarks, logos and service marks ("<em>Marks</em>") displayed on the website are our property and/or the property of the company. Users are prohibited from using any Marks for any purpose whatsoever without our prior written permission from the company. All information and content including on or through the site ("<em>Content</em>") is protected by copyright. Users are prohibited from modifying, copying, distributing, transmitting, displaying, publishing, selling, licensing, creating derivative works or using any content available on or through the site for commercial or public purposes.</li>
                <li>The Site contains copyrighted material, trademarks and other proprietary information, including, but not limited to, text, software, photos, video, graphics, music, sound, and the entire contents of the company protected by copyright as a collective work under the applicable copyright laws. The company owns a copyright in the selection, coordination, arrangement and enhancement of such content, as well as in the content original to it. Users may not modify, publish, transmit, participate in the transfer or sale, create derivative works, or in any way exploit, any of the content, in whole or in part. Users may download / print / save copyrighted material for the User's personal use only. Except as otherwise expressly stated under copyright law, no copying, redistribution, retransmission, publication or commercial exploitation of downloaded material without the express permission of the Company and the copyright owner is permitted. If copying, redistribution or publication of copyrighted material is permitted, no changes in or deletion of author attribution, trademark legend or copyright notice shall be made. The User acknowledges that he/she/it does not acquire any ownership rights by downloading copyrighted material. Trademarks that are located within or on the site or a website otherwise owned or operated in conjunction with the company shall not be deemed to be in the public domain but rather the exclusive property of the Company, unless such site is under license from the trademark owner thereof in which case such license is for the exclusive benefit and use of the Company, unless otherwise stated.</li>
                </ol>
                </li><br />
                <li><strong>PRIVACY- </strong>Users of the website and Services should refer to the Company's Privacy Policy for information about how the Company uses, collects and discloses information to third parties. Our Privacy Policy, which is hereby incorporated into this Agreement, explains how the Company treats your personal information, and protects your privacy, when you access the Application.</li><br />
                <li><strong>THIRD-PARTY LINKS- </strong>The Products and Services may contain links to third-party websites, advertisers, services, special offers, or other events or activities that are not owned or controlled by the Company. The Company does not endorse or assume any responsibility for any such third-party Websites, information, materials, products, or services. If you access a third party website from the Products and Services, you do so at your own risk, and you understand that this Agreement and the Company's Privacy Policy do not apply to your use of such Websites. You expressly relieve the Company from any and all liability arising from your use of any third-party website, service, or content. Additionally, your dealings with or participation in promotions of advertisers found on the Products and Services, including payment and delivery of goods, and any other terms (such as warranties) are solely between you and such advertisers. You agree that the Company shall not be responsible for any loss or damage of any sort relating to your dealings with such advertisers.</li><br />
                <li><strong>INDEMNITY</strong>
                <ol>
                <li>You agree to defend, indemnify and hold harmless the Company and its subsidiaries, agents, licensors, managers, and other affiliated companies, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from: (i) your use of and access to the website and Products and Services, including any data or content transmitted or received by you; (ii) your violation of any term of this Agreement, including without limitation your breach of any of the representations and warranties above; (iii) your violation of any third-party right, including without limitation any right of privacy or Intellectual Property Rights; (iv) your violation of any applicable law, rule or regulation; (v) any claim or damages that arise as a result of any of your User Content or any that is submitted via your account; or (vi) any other party's access and use of the Service with your unique username, password or other appropriate security code.</li>
                <li>Further, you agree that, if you are using our Services on behalf of a business, that business accepts these terms. It will hold harmless and indemnify the Company and its affiliates, officers, agents, and employees from any claim, suit or action arising from or related to the use of the Products and Services or violation of any of these terms, including any liability or expense arising from claims, losses, damages, suits, judgments, litigation costs and attorneys' fees.</li>
                </ol>
                </li><br />
                <li><strong>COMPANY'S LIABILITY FOR ITS SERVICES-</strong>
                <ol>
                <li>It is agreed by you that, when permitted by law, the Company will not in any way be responsible for any loss of profits, revenues, or data, financial losses or indirect, special, consequential, exemplary, or punitive damages. In all cases, the Company will not be liable for any loss or damage that is not reasonably foreseeable.</li>
                <li>Provided the liability of the Company shall not extend the amount as paid by the respective user for the services.</li>
                </ol>
                </li><br />
                <li><strong>INTERPRETATION- </strong>The Company shall have the exclusive right to interpret the Terms of Use and other policies including any future amendment.</li><br />
                <li><strong>Dispute Resolution- </strong>If any dispute, controversy or claim arises under this Agreement, including any question regarding the existence, validity or termination of this Agreement (hereinafter &ldquo;Dispute&rdquo;), the parties shall use all reasonable endeavours to resolve such Dispute amicably through mediation and consultation. If the parties are unable to resolve the Dispute amicably within 30 (Thirty) days of the notice of such Dispute, the Parties shall resolve any Dispute by a binding arbitration in accordance with the provisions of the Indian Arbitration &amp; Conciliation Act, 1996 (hereinafter mentioned to asto as "Act"). The Dispute shall be resolved by a sole arbitrator, mutually appointed in accordance with the Act. <br /><br />  The seat of the arbitration shall be New Delhi and the language of this arbitration shall be English. Either party may seek any interim or preliminary relief from a court of competent jurisdiction in New Delhi. Any arbitration shall be confidential, and the Parties shall not disclose the existence, content or results of any arbitration, except as may be required by law or for purposes of enforcing the arbitral award. All administrative fees and expenses of arbitration will be divided equally between the Parties. In all arbitrations, each party will bear the expense of its own lawyers and preparation. This paragraph shall survive termination of this Agreement.</li><br />
                <li><strong>GOVERNING LAW AND JURISDICTION- </strong>Any dispute or claim arising out of or in connection with the Policies shall be governed by and construed in accordance with the law of The Republic of India and the courts of Delhi, India shall have the exclusive jurisdiction to entertain any disputes.</li><br />
                <li><strong>LEGAL- </strong>The Company reserves the right in its sole discretion to investigate and take legal action against anyone who engages in any illegal or prohibited conduct or otherwise violates these Terms of Use, including without limitation, removing the User Content from the web-site and/or terminating the offending User's ability to access the web-site and/or use the services.</li><br />
                <li><strong>NO OBJECTION- </strong>User hereby express that it has no objection upon any call/SMS/ Communication by the Company, any third party on its behalf or any other party authorized by the Company, communicating to User with regard to the Services. Notwithstanding User's registration with National Do Not Call Registry (In Fully or Partly blocked category under National Customer Preference Register set up under Telecom Regulatory Authority of India), User hereby expresses his interest and accord its willful consent to receive communication (including commercial communication) in relation to the Company&rsquo;s Services. User further confirms that any communication, as mentioned hereinabove, shall not be construed as Unsolicited Commercial Communication under the TRAI and other alike authorities in other country&rsquo;s guidelines and User has specifically opted to receive communication in this regard on the telephone number provided by the User</li>
                </ol>`
    }
];
export default LegalData;
